#!/usr/bin/env -S deno run --allow-read --allow-write

// Generates a static command registry for code/bin/rbff by scanning rbff-scripts.

const decoder = new TextDecoder();

function toPath(url: URL): string {
  return decodeURIComponent(url.pathname);
}

const scriptPath = toPath(new URL(import.meta.url));
const repoRoot = await Deno.realPath(`${scriptPath}/../../..`);

const commandsDir = `${repoRoot}/rbff-scripts/commands`;
const outFile = `${repoRoot}/code/bin/rbff.commands.gen.ts`;

async function listCommandModules(dir: string): Promise<string[]> {
  const files: string[] = [];
  try {
    for await (const entry of Deno.readDir(dir)) {
      if (!entry.isFile) continue;
      if (!entry.name.endsWith('.ts')) continue;
      if (entry.name.startsWith('_')) continue;
      files.push(entry.name);
    }
  } catch {
    return [];
  }
  files.sort();
  return files;
}

function relPath(absPath: string, root: string): string {
  if (!absPath.startsWith(root)) return absPath;
  const rel = absPath.slice(root.length);
  return rel.startsWith('/') ? rel.slice(1) : rel;
}

const modules = await listCommandModules(commandsDir);

const header = `// This file is generated by code/scripts/generate-rbff-commands.ts
// Do not edit by hand.

// deno-lint-ignore-file no-explicit-any
`;

const imports: string[] = [];
const commandRefs: string[] = [];

for (let i = 0; i < modules.length; i++) {
  const name = modules[i];
  const importName = `cmd${i}`;
  // Path from code/bin to rbff-scripts/commands
  const importPath = `../../rbff-scripts/commands/${name}`;
  imports.push(`import { command as ${importName} } from "${importPath}";`);
  commandRefs.push(importName);
}

const body = `${imports.join('\n')}

export const commands = [
${commandRefs.map((c) => `  ${c},`).join('\n')}
] as const;
`;

await Deno.writeTextFile(outFile, header + body);
console.log(`rbff: generated ${relPath(outFile, repoRoot)} (${modules.length} commands)`);
